apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fedmed-backend-hpa
  namespace: fedmed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fedmed-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fedmed-dashboard-hpa
  namespace: fedmed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fedmed-dashboard
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
