apiVersion: v1
kind: Secret
metadata:
  name: fedmed-secrets
  namespace: fedmed
  labels:
    app.kubernetes.io/name: fedmed
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "http://mlflow.fedmed.svc.cluster.local:5000"
  API_SECRET_KEY: "fedmed-production-secret-token-key-v2"
  TENSEAL_SCHEME: "CKKS"
