apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
data:
  LOG_LEVEL: "INFO"
  API_URL: "http://{{ .Release.Name }}-backend:{{ .Values.backend.port }}"
  SERVER_ADDRESS: "{{ .Release.Name }}-flower:{{ .Values.flowerServer.port }}"
  PARTITION_STRATEGY: "{{ .Values.hospitals.partitionStrategy }}"
  DIRICHLET_ALPHA: "{{ .Values.hospitals.dirichletAlpha }}"
  DATABASE_URL: "sqlite:////app/data_db/fedmed.db"
